namespace EShoppingTutorial.Core.Domain.Entities;

public class Order : IAggregateRoot
{
    // This is Id generated by EF, so it's not 'required' at creation. So we initialize with default! to silence the warning
    public OrderId Id { get; protected set; } = default!;

    // Mandatory inputs for creation
    public required CustomerId CustomerId { get; init; }
    public required Address ShippingAddress { get; init; }

    // Managed internally by business logic
    public Guid TrackingNumber { get; init; }
    public DateTime OrderDate { get; init; } = DateTime.UtcNow;
    public OrderStatus OrderStatus { get; protected set; }

    // Expose as IReadOnlyCollection to prevent external tampering
    private readonly List<OrderItem> _orderItems = [];
    public IEnumerable<OrderItem> OrderItems => _orderItems.AsReadOnly();

    // EF Core requires a parameterless constructor
    protected Order() { }

    [SetsRequiredMembers]
    public Order(CustomerId customerId, Address shippingAddress, IEnumerable<OrderItem> orderItems) : this()
    {
        ValidateCustomerId(customerId);
        ValidateOrderItems(orderItems);

        CustomerId = customerId;
        ShippingAddress = shippingAddress;

        TrackingNumber = Guid.NewGuid();
        OrderDate = DateTime.UtcNow;
        OrderStatus = OrderStatus.Created;

        AddOrderItems(orderItems);
    }

    public void AddOrderItem(OrderItem orderItem)
    {
        ArgumentNullException.ThrowIfNull(orderItem);
        ValidateMaxPriceLimit(orderItem);
        _orderItems.Add(orderItem);
    }

    public async Task ApplyTaxAsync(ITaxCalculationService taxService)
    {
        if (OrderStatus != OrderStatus.Created)
        {
            throw new BusinessRuleBrokenException("Tax can only be applied to new orders.");
        }

        var currentTotal = _orderItems.Sum(x => x.Price.Value);
        var currency = _orderItems.First().Price.Currency;

        // Delegate the complex calculation to the Domain Service
        var taxValue = await taxService.CalculateTaxAsync(ShippingAddress, currentTotal, currency);

        // System Product ID for Tax. The "Shadow Product" Approach. Create a row in your database specifically named 'Tax' and use its real ID
        const int TaxProductId = 99999;

        // Add tax as a special OrderItem or update a Tax property
        // For this example, let's assume we add it as an order item:
        var taxItem = new OrderItem(
            productId: new ProductId(TaxProductId), // System Product ID for Tax
            price: taxValue
        );

        _orderItems.Add(taxItem);
    }

    public void MarkAsCancelled()
    {
        if (OrderStatus is not OrderStatus.Created)
        {
            throw new BusinessRuleBrokenException("Only orders in 'Created' state can be cancelled.");
        }

        OrderStatus = OrderStatus.Cancelled;
    }

    public void MarkAsPending()
    {
        if (OrderStatus is not OrderStatus.Created)
        {
            throw new BusinessRuleBrokenException("Only orders in 'Created' state can be suspended.");
        }

        OrderStatus = OrderStatus.Pending;
    }

    public void MarkAsShipped()
    {
        if (OrderStatus is not OrderStatus.Pending)
        {
            throw new BusinessRuleBrokenException($"Order cannot be shipped in its current state: {OrderStatus}.");
        }

        OrderStatus = OrderStatus.Shipped;
    }

    private void AddOrderItems(IEnumerable<OrderItem> orderItems)
    {
        foreach (var orderItem in orderItems)
        {
            ValidateMaxPriceLimit(orderItem);
            _orderItems.Add(orderItem);
        }
    }

    private static void ValidateOrderItems(IEnumerable<OrderItem> orderItems)
    {
        if (orderItems is null || !orderItems.Any())
        {
            throw new BusinessRuleBrokenException("Order must have at least one item.");
        }
    }

    private void ValidateMaxPriceLimit(OrderItem orderItem)
    {
        var currency = orderItem.Price.Currency;
        var maximumPriceLimit = MaximumPriceLimits.GetMaximumPriceLimit(currency);
        var sumPriceOfOrderItems = _orderItems.Sum(en => en.Price.Value);

        if (sumPriceOfOrderItems + orderItem.Price.Value > maximumPriceLimit)
        {
            throw new BusinessRuleBrokenException("Maximum price has been reached!");
        }
    }

    private static void ValidateCustomerId(CustomerId customerId)
    {
        if (customerId is null || customerId.Value == 0)
        {
            throw new BusinessRuleBrokenException("You must supply Customer Id!");
        }
    }
}