namespace EShoppingTutorial.Core.Domain.Entities;

public class Order : IAggregateRoot
{
    // This is Id generated by EF, so it's not 'required' at creation. So we initialize with default! to silence the warning
    public OrderId Id { get; protected set; } = default!;

    // Mandatory inputs for creation
    public required CustomerId CustomerId { get; init; }
    public required string ShippingAddress { get; init; }

    // Managed internally by business logic
    public Guid TrackingNumber { get; init; }
    public DateTime OrderDate { get; init; } = DateTime.UtcNow;
    public OrderStatus OrderStatus { get; protected set; }

    // Expose as IReadOnlyCollection to prevent external tampering
    private readonly List<OrderItem> _orderItems = [];
    public ICollection<OrderItem> OrderItems => _orderItems.AsReadOnly();

    // EF Core requires a parameterless constructor
    protected Order() { }

    [SetsRequiredMembers]
    public Order(CustomerId customerId, string shippingAddress, IEnumerable<OrderItem> orderItems) : this()
    {
        ValidateCustomerId(customerId);
        ValidateShippingAddress(shippingAddress);
        ValidateOrderItems(orderItems);

        CustomerId = customerId;
        ShippingAddress = shippingAddress;

        TrackingNumber = Guid.NewGuid();
        OrderDate = DateTime.UtcNow;
        OrderStatus = OrderStatus.Created;

        AddOrderItems(orderItems);
    }

    private static void ValidateOrderItems(IEnumerable<OrderItem> orderItems)
    {
        if (orderItems is null || !orderItems.Any())
        {
            throw new BusinessRuleBrokenException("Order must have at least one item.");
        }
    }

    public void AddOrderItem(OrderItem orderItem)
    {
        ArgumentNullException.ThrowIfNull(orderItem);
        ValidateMaxPriceLimit(orderItem);
        _orderItems.Add(orderItem);
    }

    public void MarkAsCancelled()
    {
        if (OrderStatus != OrderStatus.Created)
        {
            throw new BusinessRuleBrokenException("Only orders in 'Created' state can be cancelled.");
        }

        OrderStatus = OrderStatus.Cancelled;
    }

    public void MarkAsShipped()
    {
        if (OrderStatus is not (OrderStatus.Created or OrderStatus.Pending))
        {
            throw new BusinessRuleBrokenException($"Order cannot be shipped in its current state: {OrderStatus}.");
        }

        OrderStatus = OrderStatus.Shipped;
    }

    private void AddOrderItems(IEnumerable<OrderItem> orderItems)
    {
        foreach (var orderItem in orderItems)
        {
            ValidateMaxPriceLimit(orderItem);
            _orderItems.Add(orderItem);
        }
    }

    private void ValidateMaxPriceLimit(OrderItem orderItem)
    {
        var unit = orderItem.Price.Unit;
        var maximumPriceLimit = MaximumPriceLimits.GetMaximumPriceLimit(unit);
        var sumPriceOfOrderItems = _orderItems.Sum(en => en.Price.Amount);

        if (sumPriceOfOrderItems + orderItem.Price.Amount > maximumPriceLimit)
        {
            throw new BusinessRuleBrokenException("Maximum price has been reached!");
        }
    }

    private static void ValidateCustomerId(CustomerId customerId)
    {
        if (customerId is null || customerId.Value == 0)
        {
            throw new BusinessRuleBrokenException("You must supply Customer Id!");
        }
    }

    private static void ValidateShippingAddress(string shippingAddress)
    {
        if (string.IsNullOrWhiteSpace(shippingAddress))
        {
            throw new BusinessRuleBrokenException("You must supply Shipping Address!");
        }
    }
}
