namespace EShoppingTutorial.Core.Domain.Entities;

public class OrderItem
{
    // This is Id generated by EF, so it's not 'required' at creation. So we initialize with default! to silence the warning
    public OrderItemId Id { get; protected set; } = default!; 
    public required ProductId ProductId { get; init; }
    public required Price Price { get; init; }

    // This is the Foreign Key generated by EF, so it's not 'required' at creation
    public OrderId OrderId { get; protected set; } = default!;

    // EF Core requires a parameterless constructor
    protected OrderItem() { }

    [SetsRequiredMembers] 
    public OrderItem(ProductId productId, Price price)
    {
        ProductId = productId ?? throw new ArgumentNullException(nameof(productId));
        Price = price ?? throw new ArgumentNullException(nameof(price));
        Validate();
    }

    private void Validate()
    {
        if (ProductId.Value <= 0)
        {
            throw new BusinessRuleBrokenException("Product ID must be a positive value.");
        }

        if (!Price.HasValue)
        {
            throw new BusinessRuleBrokenException("Price cannot be negative.");
        }
    }
}
