namespace EShoppingTutorial.Core.Domain.Entities;

public class Product : IAggregateRoot
{
    // This Id is generated by EF, so it's not 'required' at creation. We initialize with default! to silence the warning.
    public ProductId Id { get; protected set; } = default!;

    // Private setters protect the entity's state
    public string Name { get; private set; }
    public string? Description { get; private set; }

    // The price is mandatory and immutable (init) upon creation
    public required Price Price { get; init; }

    // EF Core requires a parameterless constructor
    protected Product() { }

    [SetsRequiredMembers]
    public Product(string name, string description, Price price)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new BusinessRuleBrokenException("Product name is required.");

        Name = name;
        Description = description ?? string.Empty;
        Price = price ?? throw new ArgumentNullException(nameof(price));
    }
}